swagger: "2.0"
info:
  title: "Pharma-API"
  description: "API Gateway con Cloud Run"
  version: "1.0.0"
schemes:
  - "https"
paths:
  /v1/tests:
    post:
      summary: "Ejemplo de llamada POST a Cloud Run"
      operationId: "post-tests"
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - api_key: []
      x-google-backend:
        address: "https://service-template-python-487763415581.us-central1.run.app"
        path_translation: "APPEND_PATH_TO_ADDRESS"
      x-google-cors:
        allowOrigins: ["*"]
        allowMethods: ["POST"]
        allowHeaders: ["Content-Type", "Authorization"]
      responses:
        "200":
          description: "Respuesta exitosa"
        "400":
          description: "Solicitud inválida"
  /v1/token:
    post:
      summary: "endpoints autentication a Cloud Run"
      operationId: "post-tokens"
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - api_key: []
      x-google-backend:
        address: "https://pharmagob-manager-auth-487763415581.us-central1.run.app"
        path_translation: "APPEND_PATH_TO_ADDRESS"
      x-google-cors:
        allowOrigins: ["*"]
        allowMethods: ["POST"]
        allowHeaders: ["Content-Type", "Authorization"]
      responses:
        "200":
          description: "Respuesta exitosa"
        "400":
          description: "Solicitud inválida"
  /v1/token/refresh:
    post:
      summary: "Refresh de tokens"
      operationId: "post-refresh"
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - api_key: []
      x-google-backend:
        address: "https://pharmagob-manager-auth-487763415581.us-central1.run.app"
        path_translation: "APPEND_PATH_TO_ADDRESS"
      x-google-cors:
        allowOrigins: ["*"]
        allowMethods: ["POST"]
        allowHeaders: ["Content-Type", "Authorization"]
      responses:
        "200":
          description: "Token refrescado exitosamente"
        "400":
          description: "Solicitud inválida"

securityDefinitions:
  api_key:
    in: query
    name: key
    type: apiKey

