swagger: "2.0"
info:
  title: "Pharma-API"
  description: "API Gateway con Cloud Run"
  version: "1.0.0"
schemes:
  - "https"
paths:
  /v1/tests:
    post:
      summary: "Ejemplo de llamada POST a Cloud Run"
      operationId: "post"
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - keycloak: []
      x-google-backend:
        address: "https://service-template-python-487763415581.us-central1.run.app"
        path_translation: "APPEND_PATH_TO_ADDRESS"
      x-google-cors:
        allowOrigins: ["*"]
        allowMethods: ["POST"]
        allowHeaders: ["Content-Type", "Authorization"]
      responses:
        "200":
          description: "Respuesta exitosa"
        "400":
          description: "Solicitud inválida"

securityDefinitions:
  api_key:
    in: query
    name: key
    type: apiKey
  keycloak:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "http://34.127.79.17/realms/<realm>"  # <- emisor del token
    x-google-jwks_uri: "http://34.127.79.17/realms/<realm>/protocol/openid-connect/certs"
    x-google-audiences: "traxion-farma_gob-farmacias-back"  # <- ID del cliente que emite Keycloak

